# A Docker Compose must always start with the version tag.
version: "3.8"

services:
  database:
    # Official Postgres image from DockerHub
    image: "postgres"
    # By default, a Postgres database is running on the 5432 port.
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: cobrando # The PostgreSQL default database (automatically created at first launch)

  api:
    build:
      context: ./server
    container_name: cobrando_api
    ports:
      - "1234:1234"
    volumes:
      - "./server:/api"
      - "/api/node_modules"

    links: [database]

  client:
    build:
      context: ./client
    container_name: cobrando_client
    ports:
      - "3000:3000"
    volumes:
      - "./client:/client"
      - "/client/node_modules"

    links: [api]
